Adding new features folder structure
bitmonspace/website pull request #1
Opened 2021-09-30 01:05 UTC by dbeetoven

- Folder Structure
- Adding dev dependencies
- Adding Configs

2021-09-30 22:18 UTC, MarkosAg requested changes
Pending to merge. Pending to update "days text".

2021-09-30 22:18 UTC, MarkosAg commented on src/utils/dateFormat.ts
> +format(new Date(), "'Today is a' eeee");
Shouldn't be 'Today is '?

2021-10-01 03:24 UTC, dbeetoven commented on src/utils/dateFormat.ts
> +format(new Date(), "'Today is a' eeee");
This is a utils file, Actually, like a blank page, should be updated next sprint.

2021-10-01 03:56 UTC, pashoag requested changes
Code looks good overall! Thanks for putting up this setup, probably we'll use this as base for the marketplace project too. The only recommendation is about the usage of npm instead of the use of yarn. This is something we probably need to define in our docs in the next PRs.

Good to approve after this change.

2021-10-01 03:56 UTC, pashoag commented on .github/build-and-test.yml
> +        run: npm run type:check
🛠️ Recommended change
Updating the usage of npm to use yarn.
```suggestion
        run: yarn run type:check
```

2021-10-01 03:56 UTC, pashoag commented on .github/build-and-test.yml
> +        run: npm run test:unit
🛠️ Recommended change
Updating the usage of npm to use yarn.
```suggestion
        run: yarn run test:unit
```

2021-10-01 03:56 UTC, pashoag commented on .github/build-and-test.yml
> +        run: npm install
🛠️ Recommended change
We'll need to update this to use yarn instead of npm.
```suggestion
      - name: Run yarn install
        run: yarn install
```

2021-10-01 03:56 UTC, pashoag commented on .github/build-and-test.yml
> +          start: npm run start
🛠️ Recommended change
Updating the usage of npm to use yarn.
```suggestion
          build: yarn run build
          start: yarn run start
```

2021-10-01 03:56 UTC, pashoag commented on .github/build-and-test.yml
> +          start: npm run start
🛠️ Recommended change
Updating the usage of npm to use yarn.
```suggestion
          build: yarn run build
          start: yarn run start
```

2021-10-03 18:16 UTC, merged